insert into product(product_Name, prize, type) values ('Fable', 50, 'RPG');
insert into product(product_Name, prize, type) values ('Minecraft', 70, 'RPG');
insert into product(product_Name, prize, type) values ('Wiedźmin', 30, 'RPG');
insert into product(product_Name, prize, type) values ('Wiedźmin 2', 50, 'RPG');
insert into product(product_Name, prize, type) values ('Wiedźmin 3', 300, 'RPG');
insert into product(product_Name, prize, type) values ('Counter Strike', 100, 'FPS');
insert into product(product_Name, prize, type) values ('Stronghold', 10, 'STRATEGY');
insert into product(product_Name, prize, type) values ('Europa Universalis IV', 100, 'STRATEGY');
insert into product(product_Name, prize, type) values ('Mount and Blade', 100, 'STRATEGY');
insert into product(product_Name, prize, type) values ('Command and Conquer', 100, 'STRATEGY');
